import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Sobre from "./components/sobre";
import QuemSomos from "./components/quemsomos";
import Sistemas from "./components/sistemas";
import Contato from "./components/contato";
import Footer from "./components/footer";

const archivo = Archivo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BlockCode - Desenvolvimentod de Sistemas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body className={archivo.className}>
        <Navbar/>
        {children}
        <Sobre/>
        <QuemSomos/>
        <Sistemas/>
        <Contato/>
        <Footer/>
        </body>
    </html>
  );
}
